### ISSUE TITLE
Walk tree data

### ISSUE THREAD

**Issue by Kawacrepe** [phphe/he-tree-vue#10]
Hello guys

Do you have any sample where I can find how work with 'walkTreeData'.
Because, In my case I have a tree who can contain X nodes, and every nodes have a property which is based on a modulo % 2.

I was thinking about working with walkTreeData but I wasn't able to call this function properly.

Do you have any suggestion or workaround to walk across the tree properly?

Thank's in advance, if you need some helps to improve the plugin let me know

**Comment by phphe** [comment]
There is a `foldAll` function in fold plugin: https://github.com/phphe/he-tree-vue/blob/master/src/plugins/fold.js#L46
It walk all node and fold them.
The walk can be control by return special value: 
http://localhost:8081/api.html#walktreedata
https://he-tree-vue.phphe.com/api.html#walktreedata-2
