### ISSUE TITLE
router-links and click events inside a tree node do not work on touch devices 

### ISSUE THREAD

**Issue by joostdelange** [phphe/he-tree-vue#12]
Hi,

My team and I are using he-tree-vue in a few of our projects, also in combination with the pro version.
We noticed router-links, click events (also <a> tags) are not triggered on touch devices.
This is only when using the **Draggable** plugin imported using the `mixPlugins` method.

You can even reproduce it in the demo's from the guide: https://he-tree-vue.phphe.com/guide.html#customize

You can test this yourself by either opening it on an actual touch device or toggling on the device toolbar in the Chrome Devtools. You'll notice links and click events are not triggered.

We would appreciate it if you can take a look at this!

**Comment by phphe** [comment]
Thank you. fixed in 1.2.2 
The docs site also updated: https://he-tree-vue.phphe.com/guide.html#customize

**Comment by joostdelange** [comment]
Thanks for the quick fix, can confirm click events now work on touch devices! Closing the issue 🙂

**Comment by b2vincent** [comment]
Thank you for the fix. I had just noticed yesterday the problem with clickable links on touch devices.
