### ISSUE TITLE
tree-branch transition move weird

### ISSUE THREAD

**Issue by seonglae** [phphe/he-tree-vue#13]
if i add transition time to  tree-branch like this
```
.tree-branch {
  transition: all 20s ease;
}
```

it moves really weird not smooth
tthis feature make tree more beatiful!

**Comment by phphe** [comment]
It's a good feature. But it's too difficult to develop. I will develop it this week, and I want put it into the pro version.

**Comment by phphe** [comment]
Hi. I tried to develop this feature in v2. I found it is difficult and rarely used. So I gave up this feature.

**Comment by seonglae** [comment]
what a sad news!
