### ISSUE TITLE
Selected/active state of the node?

### ISSUE THREAD

**Issue by OdiljonQurbon** [phphe/he-tree-vue#14]
Awesome project, thank you!
A question. Is a click event available for the node? I mean, if I want to do some actions on click on top of the node what should I do?

**Comment by phphe** [comment]
Custom node template, then you can listen any event. Example: https://he-tree-vue.phphe.com/guide.html#custom-display-through-default-slot
```html
<span slot-scope="{node, index, path, tree}">
to
<span slot-scope="{node, index, path, tree}" @click="yourNodeClickHandler(node)">
```
If you use jsx like this: https://he-tree-vue.phphe.com/source.html#demo6
```jsx
<div class="node-content">
to
<div class="node-content" onClick={()=>this.yourNodeClickHandler(node)}>
```

**Comment by OdiljonQurbon** [comment]
Cool. I emitted from the child directly to the parent component using jsx way:
```js
onClick={() => this.$parent.myNodeClickedHandler(node)}
```
Thanks!

**Comment by sanjogs** [comment]
@OdiljonQurbon Were you able to set highlighted state on the selected node? I am extending the tree component and creating node using overrideSlotDefault, upon clicking the node overrideSoltDefault obviously doesn't fire, so i am wondering how can we set the selected state.

@phphe Any ideas on how to achieve this?
