### ISSUE TITLE
I suggest some features

### ISSUE THREAD

**Issue by seonglae** [phphe/he-tree-vue#15]
- Multi Select by Drag
- Multi drop after multi drag and drop
- Vertical divider like Notion.so

Is these features are in repository's plan or already possible?
### It will be great repository if it could be

**Comment by phphe** [comment]
Multi Select and Multi drop are too difficult to develop in this tree component. I think they are usually used in conjunction with list components. So I don't want to implement the 2 features.

Vertical divider: What it, I can't find it in Notion.so.

**Comment by seonglae** [comment]
![image](https://user-images.githubusercontent.com/27716524/80439495-a0b02780-8941-11ea-8e71-6b18db67930a.png)
This is [My Page](https://www.notion.so/seongland/Seong-Land-04089c8ae3534bf79512fc495944b321)

Actually not divider, vertical dividing by block type (vertical dividing block's children shown in vertical view)

**Comment by phphe** [comment]
It seems more difficult. I have no idea.

**Comment by seonglae** [comment]
Sorry My explanation is bad!😂
