### ISSUE TITLE
[Feature] allowSiblingsAbove prop

### ISSUE THREAD

**Issue by jonayrodriguezmrf** [phphe/he-tree-vue#18]
is it possible to create a prop like draggable or droppable?
by `default: true`

avoid dragging an item over another item as shown in the GIF
![feat](https://user-images.githubusercontent.com/36264905/82228489-7989bc00-9929-11ea-853a-ef88fdf58295.gif)

**Comment by phphe** [comment]
If you mean draggable or droppable for node, you can set $draggable or $droppable of node. If you want to set them for many nodes quickly, you can give a function to tree's prop eachDraggable or eachDroppable: https://he-tree-vue.phphe.com/api.html#eachdraggable
