### ISSUE TITLE
In your demo code, about returning HTML codes... 

### ISSUE THREAD

**Issue by KLA6** [phphe/he-tree-vue#19]
First of all, thank you for your great work...!

In your demo source https://he-tree-vue.phphe.com/source.html#demo6 ...

There is a part as below.

```
return <div class="node-content">
  <button class="mrs drag-trigger">Drag</button>
  <button class="mrs fold-btn" onClick={() => tree.toggleFold(node, path)}>{node.$folded ? '+' : '-'}</button>
  {original()}
  <button class="mls">edit</button>
  <button class="mls" onClick={() => this.removeNodeByPath(path)}>remove</button>
  <button class="mls" onClick={() => this.hideNode(node)}>hidden</button>
</div>
```

I think this must because of my short knowledge of Vue.js, but it makes an error as below.

![image](https://user-images.githubusercontent.com/10718444/83409000-c5665600-a43d-11ea-82a5-c8c99c5f3002.png)

Can I ask how the demo source is possible to be run...?

Do I need to install another NPM for the JS grammar...?

**Comment by phphe** [comment]
This template is jsx grammar. If you use vue-cli, jsx should be supported by default.
https://vuejs.org/v2/guide/render-function.html

**Comment by KLA6** [comment]
Ah, thank you so much for your guide...!

Just a record for someone like me, the below is required.
https://github.com/vuejs/babel-plugin-transform-vue-jsx
