### ISSUE TITLE
unfoldWhenDragover open delay

### ISSUE THREAD

**Issue by davidboom95** [phphe/he-tree-vue#2]
Hello, 
Does the tree has a Delay API for this prop?
In Webcat.app we are coming from vue-draggable-nested-tree
Thank you!

**Comment by phphe** [comment]
I need more about your requirement.

**Comment by phphe** [comment]
delay is available in 1.2.0: https://he-tree-vue.phphe.com/api.html#unfoldwhendragoverdelay
