### ISSUE TITLE
【Q】How do I set up the tree-children class?

### ISSUE THREAD

**Issue by djkloop** [phphe/he-tree-vue#22]
## How do I set up the tree-children class?

![image](https://user-images.githubusercontent.com/21050914/84647034-76d4b380-af35-11ea-954d-3c761bca8dc6.png)

![image](https://user-images.githubusercontent.com/21050914/84647367-f06ca180-af35-11ea-9bf6-5a0d22aa0453.png)

### use slot 
![image](https://user-images.githubusercontent.com/21050914/84647549-29a51180-af36-11ea-8a4d-22a6bc7a10c8.png)

```
///  I need to add lines...
///  I use the slot method to render the label
///  Is tree-children padding-lef the same as tree-node-back?
```
![image](https://user-images.githubusercontent.com/21050914/84648096-09c21d80-af37-11ea-96c4-03fb9c1f6376.png)

**Comment by phphe** [comment]
https://he-tree-vue.phphe.com/api.html#xxxclass

**Comment by djkloop** [comment]
搞定了，能问下，tree-children 这个类和tree-node-back 这个为什么不能保持一致的padding呢？就是也同样保持缩进？我看了下样式里面他的children都是占满一整行的。上面发的最后一张图

**Comment by phphe** [comment]
那样就双重缩进了. tree-node-back占满一行是为了做全宽背景.
