### ISSUE TITLE
More complex example

### ISSUE THREAD

**Issue by serbeh** [phphe/he-tree-vue#23]
Hello! Great project!
But could you provide little bit more complex example with undraggable and undroppable single nodes. Something like this example for _vue-draggable-nested-tree_ (https://codepen.io/phphe/pen/KRapQm)? Or some example of functions for **droppable** / **draggable**.
Actually, I need to make undroppable thoes nodes that have no children. Is it easy to implement?

**Comment by phphe** [comment]
```js
 {text: 'node 3 undraggable', $draggable: false},
 {text: 'node 4'},
 {text: 'node 4 undroppable', $droppable: false},
```
https://he-tree-vue.phphe.com/api.html#draggable-2
