### ISSUE TITLE
cannot drag and drop nodes

### ISSUE THREAD

**Issue by et84121** [phphe/he-tree-vue#24]
從 chrome console 裡看到是這行引起的
TypeError: Cannot read property 'map' of undefined
https://github.com/phphe/he-tree-vue/blob/0f9078b3e3e04c8b9b0bbb227a7af85b81cb0eea/src/components/Tree.vue#L52
似手 `nodes` 是一個 `undefined` 值導致

![image](https://user-images.githubusercontent.com/9102619/85375190-858c1d80-b568-11ea-923c-fd178ef21121.png)

但神奇的是我只要修改一下 該 treeView component
透過 Webpack hot reload 的機制
拖曳功能就又恢複正常了

**Comment by et84121** [comment]
here is the problem code
https://codesandbox.io/s/loving-merkle-7dddk

**Comment by phphe** [comment]
https://codesandbox.io/s/relaxed-burnell-6vwo4
I changed sunburstData:undefined to sunburstData:[]
The initial data can't be null
```js
data() {
    return {
      sunburstData: []
    };
  },
```

**Comment by et84121** [comment]
Really thank you a lot.
Sorry to bother you for the careless mistake. 😅😅😅
I will close this issue.
