### ISSUE TITLE
Typescript issue with mixPlugins function

### ISSUE THREAD

**Issue by Steveiwonder** [phphe/he-tree-vue#28]
![image](https://user-images.githubusercontent.com/1899448/89629837-633f2c80-d896-11ea-81f6-c380c43de0c5.png)

![image](https://user-images.githubusercontent.com/1899448/89629890-73570c00-d896-11ea-960b-cdac972d5509.png)

Current workaround
![image](https://user-images.githubusercontent.com/1899448/89631242-6c30fd80-d898-11ea-972d-60adc9ec606a.png)

**Comment by phphe** [comment]
Hi

mixPlugins is not defined in typescript because  I can't describe its return with TS. My suggestion is to create your TreeView component.
```ts
export default class App extends Mixins(Tree, Fold, Check, Draggable) {...}
```
Full example: https://github.com/phphe/vue-cli-typescript-he-tree-test/blob/master/src/components/TreeView/index.tsx
