### ISSUE TITLE
edgeScroll: define which scroll container to scroll

### ISSUE THREAD

**Issue by dswbx** [phphe/he-tree-vue#29]
just evaluating this library and looks promising, thanks a lot! 

Although something I've encountered: My tree is within a sidebar component (fixed, own scroll). So having a long tree I need scrolling. Enabling `edgeScroll` though scrolls down the whole document (therefore the main component) instead of my sidebar only. Is there a way to specify which container should be scrolled?

**Comment by phphe** [comment]
No. I am going to add it.

**Comment by dswbx** [comment]
@phphe thanks a lot :)

**Comment by phphe** [comment]
try 2.0.4-beta2 . I added prop: edgeScrollSpecifiedContainerX, edgeScrollSpecifiedContainerY
```ts
edgeScrollSpecifiedContainerX?: HTMLElement | ((store: Store, opt: Options) => HTMLElement);
edgeScrollSpecifiedContainerY?: HTMLElement | ((store: Store, opt: Options) => HTMLElement);
```

**Comment by dswbx** [comment]
Awesome, thank you!
