### ISSUE TITLE
Please reply to your emails

### ISSUE THREAD

**Issue by ghost** [phphe/he-tree-vue#3]
Hi Xinxin,

My team and I tried contacting you through email about the purchase of he-tree-vue pro. We still have not received any information where we can get the package we purchased.

I'm sorry for reaching out to you this way, but we've sent numerous request to you. This has been 3 weeks already, and I still haven't received an answer. I see that you're active on Github, so please also reply to us.

Best regards,

**Comment by phphe** [comment]
Hi
I havn't received your email. I just received your paypal and github notification. Please make sure that my email is phphe@outlook.com. And your email is rick@indexonline.nl when purchased. I have sent 2 mails to that address. Please specified another address if you still not received.

**Comment by ghost** [comment]
Hi
Thanks man,

Really weird. Thanks for reaching out! Maarten has indeed now received the package by mail.

**Comment by phphe** [comment]
Hi
Please cancel the refund request on paypal if everything is ok.
