### ISSUE TITLE
Update parent_id and path after dragging and dropping element

### ISSUE THREAD

**Issue by mahoone** [phphe/he-tree-vue#30]
Hi,

How can I update values in parent_id and path after drag and drop event is completed?

So for example I have the below structure:

![image](https://user-images.githubusercontent.com/29840139/90499313-abd5d000-e149-11ea-88ec-3044ea6bbb53.png)

As you can see the 3rd element with id of 363 has wrong parentId of 54 (should be 55) and path should be 1 instead of 2 as it is a first element in that array.

Any idea how can I update those values dynamically so I can then save them back into mysql?

Many thanks for your help!

**Comment by phphe** [comment]
do that in event 'drop'. `store.dragNode` is the dragged node.
```js
ondrop(store){
  let parent = tree.getNodeParentByPath(store.targetPath)
  store.dragNode.parentId = parent .id
  store.dragNode.path = parent.children.indexOf(store.dragNode)
}
```

**Comment by mahoone** [comment]
Thank you!
How can I access 'tree' and 'store'? Where should I declare those? Sorry if it's too obvious!

Here's my code:

`<template>
  <div>
    <v-row class="mb-6" no-gutters>
      <v-col md="6">
        <Tree
          v-bind:value="systemMenuItems"
          foldAllAfterMounted
          draggable
          ref="tree"
          droppable
          edgeScroll
          class="systemMenuTree"
          @drop="setCurrentNode(store)"
        >
          <span slot-scope="{node, index, path, tree}">
            
            <input type="checkbox" :checked="node.active" @change="tree.toggleCheck(node, path)" />
            
            <span
              v-if="node.children && node.children.length"
              @click="tree.toggleFold(node, path)"
            >{{node.$folded ? '+' : '-'}}</span>
            {{node.path}}
            {{node.text}}
            <i>{{path.join(',')}}</i>
            
            
          </span>
        </Tree>
      </v-col>
      <v-col md="6">
        <v-spacer></v-spacer>
        <pre>{{ systemMenuItems}}</pre>
      </v-col>
    </v-row>
  </div>
</template>

<script>
import draggable from "vuedraggable";
import axios from "axios";
import {
  Tree, // Base tree
  Fold,
  Check,
  Draggable, // plugins
  foldAll,
  unfoldAll,
  cloneTreeData,
  walkTreeData,
  getPureTreeData, // utils
} from "he-tree-vue";
import "he-tree-vue/dist/he-tree-vue.css";

export default {
  data() {
    return {
      // Aktualny node
      currentNode: [],
      // Zmodyfikowane menu systemowe
      updatedMenuItems: [],
      // Menu systemowe
      systemMenuItems: [],
      selectedItems: [],
    };
  },
  mounted() {},
  props: {},
  created() {
    this.loadSystemMenu();
  },
  computed: {},
  components: {
    draggable,
    Tree: Tree.mixPlugins([Draggable, Fold, Check]),
  },
  methods: {
    // Pobiera menu systemowe z DB
    loadSystemMenu() {
      axios
        .get("/api/companyitems")
        .then(({ data }) => (this.systemMenuItems = data));
    },
    edit(node) {
      node.text = window.prompt("Edit node", node.text);
    },
    update() {
      this.systemMenuItems.map((node, key) => {
        node.path = key + 1;
      });
      this.systemMenuItems[0].children.map((node, key) => {
        node.path = key + 1;
      });
      // Wyslanie danych do bazy danych
      // axios
      //   .put("/api/systemmenu/{}", {
      //     updatedMenuItems: this.systemMenuItems,
      //   })
      //   .then((respose) => {
      //     console.log("Wyslano menu systemowe");
      //   });
    },
    // this.systemMenuItems[0].children.push({ text: "child" });
    setCurrentNode(store) {
      let parent = tree.getNodeParentByPath(store.targetPath);
      store.dragNode.parentId = parent.id;
      store.dragNode.path = parent.children.indexOf(store.dragNode);
      console.log("logged");
      // console.log(this.test);

      // this.currentNode = node;

      // if (this.currentNode.parentId != "0") {
      //   console.log("child");
      // } else {
      //   console.log("parent");
      // }
    },
  },
};
</script>

<style>
.systemMenuTree .tree-node {
  padding: 5px;
  border-radius: 5px;
}
</style>
`

**Comment by phphe** [comment]
```html
<Tree ref="tree" @drop="ondrop">
  ...
</Tree>
```
then access tree by `this.$refs.tree`
store is the first argument of ondrop

**Comment by mahoone** [comment]
Thank you!
I'm doing something wrong because I keep getting 'undefined' errors. Sorry if it's too obvious!

**Comment by phphe** [comment]
change @drop="ondrop(store)" to @drop="ondrop"

**Comment by mahoone** [comment]
Now I'm getting: Cannot read property 'targetPath' of undefined". Am I accessing store correctly in Methods? 

```
ondrop() {
      var tree = this.$refs.tree;
      var store = this.store;
      let parent = tree.getNodeParentByPath(store.targetPath);
      store.dragNode.parentId = parent.id;
      store.dragNode.path = parent.children.indexOf(store.dragNode);
      console.log("logged");
      // console.log(this.test);

      // this.currentNode = node;

      // if (this.currentNode.parentId != "0") {
      //   console.log("child");
      // } else {
      //   console.log("parent");
      // }
    },
```

**Comment by phphe** [comment]
change ondrop() to ondrop(store)
```js
@drop="ondrop" is in template
ondrop(store) is in js
```

**Comment by mahoone** [comment]
Thank you. It is updating now with the correct parentId. 

Do you know how can I resolve the path issue?

My current 'path system' is as follows:

```
[
  {
    "id": 54,
    "text": "Administracja",
    "parentId": 0,
    "path": 19,
    "active": 1,
    "children": [
      {
        "id": 55,
        "text": "Struktura menu systemu",
        "parentId": 54,
        "path": 1,
        "active": 1
      },
      {
        "id": 363,
        "text": "Zarządzanie profilami dostępu",
        "parentId": 54,
        "path": 2,
        "active": 1
      },
      {
        "id": 497,
        "text": "Zarządzanie użytkownikami",
        "parentId": 54,
        "path": 3,
        "active": 1,
        "children": [
          {
            "id": 503,
            "text": "Dodawanie nowego pracownika",
            "parentId": 497,
            "path": 1,
            "active": 1
          },
          {
            "id": 504,
            "text": "Modyfikacja danych pracownika",
            "parentId": 497,
            "path": 2,
            "active": 1
          },
```

Can I implement path system that the nodes are using which is 0 -> 0,0 -> 0,0,0 and so on into my application instead of using my 'path' system?

Many thanks!

**Comment by phphe** [comment]
```js
ondrop(store){
  let parent = tree.getNodeParentByPath(store.targetPath)
  store.dragNode.parentId = parent .id
  store.dragNode.path = parent.children.indexOf(store.dragNode) + 1
}
```

**Comment by mahoone** [comment]
Thank you! It does work when dragging nodes up but when moved down it doesn't change anything: 

![image](https://user-images.githubusercontent.com/29840139/90763979-eaa18c80-e2e7-11ea-8bd7-8c03608d989e.png)

Any idea how can I fix that? 
So when I move a child down it should update it's path and other child's paths.

Thank you!

**Comment by phphe** [comment]
```js
ondrop(store){
  let fromParent = tree.getNodeParentByPath(store.startPath)
  fromParent.children.forEach((child, index) => {
    child.path = index + 1
  })
  let targetParent = tree.getNodeParentByPath(store.targetPath)
  store.dragNode.parentId = targetParent.id
  targetParent.children.forEach((child, index) => {
    child.path = index + 1
  })
}
```

**Comment by mahoone** [comment]
Thank you so much for all your help. I think it's all good now!

![menusystemowe](https://user-images.githubusercontent.com/29840139/90768267-bed5d500-e2ee-11ea-9b01-d2b598d2b612.gif)
