### ISSUE TITLE
TargetPath is updated late?

### ISSUE THREAD

**Issue by TheHussein** [phphe/he-tree-vue#33]
Hello, I'm trying to make a drag and drop tree where nodes can only be moved inside same level, to do this I used function droppable and I'm using the 2nd store parameter. startPath works fine but targetPath is being set late and is undefined, how can I work around this?
```
  methods: {
    isNodeDroppable(tree, store) {
      console.log(store);
      console.log(store.startPath + "-" + store.targetPath);
      return true;
    },
  },
```

![Screen Shot 2020-09-22 at 1 03 05 PM](https://user-images.githubusercontent.com/28165176/93876034-6a9b8780-fcd6-11ea-83bf-5c91192acec4.png)

**Comment by TheHussein** [comment]
Using eachDroppable instead of droppable fixed my issues:

```
    isNodeDroppable(currentPath, tree, treeDataStore) {
      console.log(treeDataStore.startPath + "==>" + currentPath);
      return true;
    },
```

**Comment by TheHussein** [comment]
Full code for same level same parent updates only:
```
  methods: {
    isNodeDroppable(currentPath, tree, treeDataStore) {
      let startPath = treeDataStore.startPath;
      return (
        this.isSameLevel(startPath, currentPath) &&
        this.isSameParent(startPath, currentPath)
      );
    },
    isSameLevel(startPath, currentPath) {
      if (startPath.length === currentPath.length + 1) {
        return true;
      }
      return false;
    },
    isSameParent(startPath, currentPath) {
      if (
        startPath[startPath.length - 2] !== currentPath[currentPath.length - 1]
      ) {
        return false;
      }
      return true;
    },
  },
```

**Comment by phphe** [comment]
`isNodeDroppable` is an internal method, it is not recommended to modify. It is recommended to use prop eachDroppable.
