### ISSUE TITLE
Vue 3 Support?

### ISSUE THREAD

**Issue by alabama** [phphe/he-tree-vue#34]
Any plans on supporting vue.js 3 and composition-api?

**Comment by phphe** [comment]
I just know vue3.0 released. I will try to do that.

**Comment by alabama** [comment]
is there any update so far?

**Comment by phphe** [comment]
Vue 3 supported now. Works well in Vue-CLI and Vite when test. Version `2.*.*` is for Vue 2, `3.*.*` is for Vue 3.

### For Vue 3
```sh
npm install --save he-tree-vue@3
```
### For Vue 2
```sh
npm install --save he-tree-vue@2
```
