### ISSUE TITLE
How to disable auto check childs?

### ISSUE THREAD

**Issue by d4rkr3pt0r** [phphe/he-tree-vue#35]
Is there a way to disable auto checking sub-menus by checking parent? and of course vice versa
Edit: I want to disable the above behavior also for deleting nodes. Prevent deleting childs as well.

Edit: Another question :)  How to have multiple Trees while only some of them are draggable? loading Draggable components makes them all draggable.

**Comment by phphe** [comment]
follow is the source code of toggleCheck
```js
toggleCheck(node, path) {
      this.$set(node, '$checked', !node.$checked)
      this.afterCheckChanged(node, path)
    },
```
For your request, write your method, don't include `this.afterCheckChanged(node, path)`

**Comment by d4rkr3pt0r** [comment]
> 
> 
> follow is the source code of toggleCheck
> 
> ```js
> toggleCheck(node, path) {
>       this.$set(node, '$checked', !node.$checked)
>       this.afterCheckChanged(node, path)
>     },
> ```
> 
> For your request, write your method, don't include `this.afterCheckChanged(node, path)`

Thanks. What about having multiple trees while making some of them draggable?

**Comment by phphe** [comment]
The pro version supports multiple tree draggable: https://he-tree-vue.phphe.com/buy_pro.html#licenses

**Comment by d4rkr3pt0r** [comment]
> 
> 
> follow is the source code of toggleCheck
> 
> ```js
> toggleCheck(node, path) {
>       this.$set(node, '$checked', !node.$checked)
>       this.afterCheckChanged(node, path)
>     },
> ```
> 
> For your request, write your method, don't include `this.afterCheckChanged(node, path)`

Thanks. What about having multiple trees while some of theme

> 
> 
> The pro version supports multiple tree draggable: https://he-tree-vue.phphe.com/buy_pro.html#licenses

This is not what i'm looking for. I have 3 Trees in a single page. I want just one of them to be draggable not all of them. how can I use `IsDraggable` to disable draggable on other two Trees ?

**Comment by phphe** [comment]
https://he-tree-vue.phphe.com/api.html#draggable
e.g.:
```html
<Tree :draggable="false" :droppable="false"></Tree>
```
