### ISSUE TITLE
unfoldWhenDragover not working

### ISSUE THREAD

**Issue by sam019** [phphe/he-tree-vue#37]
version: 2.0.5

**Comment by phphe** [comment]
Please recheck. It works well in the example https://codesandbox.io/s/vue-cli-and-he-tree-vue-example-k2d11?file=/src/App.vue
If you still get the issue, please create a reproduce.

**Comment by sam019** [comment]
Okay...If i drag over  tree-node element, it will unfold. But if i just drag over .tree-node-back, it will not. thanks
