### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by the-nicolas** [phphe/he-tree-vue#4]
Are there typescript definitions available for your component?

Looks really good what you did, but I would not use it in a new project without correct types...

**Comment by phphe** [comment]
I am going to create it.

**Comment by phphe** [comment]
I never use typescript on vue before. I added type definitions in 1.1.0-beta.
I created a typescript project with vue cli3, and rewrited the demo6 in docs.
original demo6: https://he-tree-vue.phphe.com/source.html#demo6
rewrited repo: https://github.com/phphe/vue-cli-typescript-he-tree-test
