### ISSUE TITLE
How to use Fold Plugin.

### ISSUE THREAD

**Issue by miyasinarafat** [phphe/he-tree-vue#5]
I tried to use fold plugin props `foldAllAfterMounted` in this example but it didn't work.

```
<template>
  <Tree :value="treeData" :foldAllAfterMounted="false">
    <span slot-scope="{node, index, path, tree}">
      <b @click="tree.toggleFold(node, path)">
        {{node.$folded ? '+' : '-'}}
      </b>
      {{node.text}}
    </span>
  </Tree>
</template>
<script>
import 'he-tree-vue/dist/he-tree-vue.css'
import {Tree, Fold} from 'he-tree-vue'

export default {
  components: {Tree: Tree.mixPlugins([Fold])},
  data() {
    return {
      treeData: [{text: 'node 1'}, {text: 'node 2', children: [{text: 'node 2-1'}]}]
    }
  },
}
</script>
```

**Comment by phphe** [comment]
foldAllAfterMounted  is false default, so the children tree is unfolded default.  so your code is equal to default.
The follow code will fold all after mounted
```html
<Tree :value="treeData" foldAllAfterMounted>
```

**Comment by miyasinarafat** [comment]
Here is my updated code:

```
<Tree :value="item_groups_tree" foldAllAfterMounted>
    <span slot-scope="{node, index, path, tree}">
      <b @click="tree.toggleFold(node, path)">
        {{node.$folded ? '+' : '-'}}
      </b>
        {{node.Name + ' ('+node.SystemKey+')'}}
    </span>
</Tree>
```
Here is the output image. `foldAllAfterMounted` is `true` now but didn't collapse the tree.
![image](https://user-images.githubusercontent.com/16781160/75319760-74235500-5897-11ea-9317-c138f41c1f98.png)

**Comment by phphe** [comment]
The tree mounted, then it try fold existed data. The data added after that will not be folded. The source code is at fold.js like follow:
```js
mounted() {
    if (this.foldAllAfterMounted) {
      this.foldAll()
    }
  },
```
So you can call tree.foldAll() manually.

**Comment by miyasinarafat** [comment]
Thanks so much for your reply.

I tried to use `tree.foldAll()`  in `mounted()` and template. but didn't work. Could you please show me how I could use `tree.foldAll()`.

**Comment by phphe** [comment]
Template
```html
<Tree :value="item_groups_tree" ref="tree">
...
</Tree>
```
In script
```js
this.$refs.tree.foldAll()
```

**Comment by miyasinarafat** [comment]
Thanks again. But I am sorry it's didn't work for me :(

**Comment by phphe** [comment]
can you show the code?

**Comment by miyasinarafat** [comment]
Here is my code:

**Templaste:**
```
<Tree :value="item_groups_tree" ref="tree">
    <span slot-scope="{node, index, path, tree}">
      <b @click="tree.toggleFold(node, path)">
        {{node.$folded ? '+' : '-'}}
      </b>
        {{node.Name + ' ('+node.SystemKey+')'}}
    </span>
</Tree>
```

**Script:**

```
mounted() {

    //this.$refs.tree.foldAll();

    if (this.foldAllAfterMounted) {
        this.$refs.tree.foldAll();
    }
}
```

I am also tried to call `this.$refs.tree.foldAll();` after init `item_groups_tree` data variable.

**Comment by phphe** [comment]
```js
mounted() {
  this.$refs.tree.foldAll();
}
```
is it works?

**Comment by miyasinarafat** [comment]
Sorry it is not working.
![image](https://user-images.githubusercontent.com/16781160/75342072-e1e37700-58bf-11ea-95c2-c3b529fb3dbe.png)

**Comment by phphe** [comment]
when is item_groups_tree ready? tree.foldAll() will walk all nodes and set $folded of each node to true. so the data must be ready before foldAll called.

**Comment by miyasinarafat** [comment]
I am also assumed that. I don't understand why it's not working?

**Comment by phphe** [comment]
check App.vue in this: https://codesandbox.io/s/vue-cli-and-he-tree-vue-example-k2d11
foldAllAfterMounted works well

**Comment by miyasinarafat** [comment]
Hi,

Thanks so much for your solutions. I flow like your component design `TreeView`.  When I call `tree.foldAll()` inside of the `overrideSlotDefault()` method then It folds all the tree node.

But the problem is when I return this content it's print as text like the below image.
```
overrideSlotDefault({ node, index, path, tree }, original) {
    tree.foldAll();
    let html =
        `<button class="mrs fold-btn" @click="${tree.toggleFold(node, path)}">${node.$folded ? "+" : "-"} </button> ${node.Name}
       `;
    return html;
    //return ((node.$folded ? "+" : "-") + node.Name);
}
```
![image](https://user-images.githubusercontent.com/16781160/75425003-039a3800-596c-11ea-9e91-93944ec6aece.png)

If I return this ` ((node.$folded ? "+" : "-") + node.Name)` then the view like this:
![image](https://user-images.githubusercontent.com/16781160/75425136-507e0e80-596c-11ea-9854-bb06ba52c1e9.png)

But If I try to use your implementation from here:( https://codesandbox.io/s/vue-cli-and-he-tree-vue-example-k2d11) then I got an error.  I am using Vue inside Laravel app.
Here is the error image:
![image](https://user-images.githubusercontent.com/16781160/75425479-fdf12200-596c-11ea-9635-ab2ebdac8528.png)

**Comment by phphe** [comment]
tree.foldAll() fold all nodes. So just get the tree and execute after your data ready. such as:
```js
httpGetData().then(data => {
this.myTreeData = data
this.$refs.tree.foldAll()
})
```
overrideSlotDefault is to custom node render. It should return jsx. It will be often called, so the foldAll shoud not be in it.

**Comment by phphe** [comment]
Sorry, there is a bug.

**Comment by miyasinarafat** [comment]
Oh, Could you please tell me what I will do now about this matter.

**Comment by phphe** [comment]
```js
this.myTreeData = data
this.$refs.tree.foldAll()
```
In this, tree will fold old data because the prop is not updated immediately. But if put this.$refs.tree.foldAll() in nextTick, the DOM will flash once.

So walk new data and set $folded=true
```js
import {walkTreeData} from 'he-tree-vue'

httpGetData().then(data => {
  this.myTreeData = data
  walkTreeData(data, node => {this.$set(node, '$folded', true)})
})
```

**Comment by miyasinarafat** [comment]
Sorry, maybe I confused you. I just told that `tree.foldAll()` only work from `overrideSlotDefault()` method not from Http get request method.

**Comment by phphe** [comment]
Is your data defined in component or get asynchronously such as by ajax?

**Comment by miyasinarafat** [comment]
Data getting by asynchronously using ajax.

**Comment by phphe** [comment]
can you show get data and assignment part?

**Comment by miyasinarafat** [comment]
Here is my component code: https://paste.ubuntu.com/p/nhfBnyK3N7/
and here is the model axios call method:

```
    static fetchTree(company_id) {

        return new Promise((resolve, reject) => {

            axios.post('/web-api/e-commerce/itemgroups/tree', {
                companyId: company_id,
            })
                .then(({data}) => {

                    resolve(data);

                })
                .catch(error => {
                    reject(error);
                });

        });
    }
```

**Comment by phphe** [comment]
```js
import {walkTreeData} from 'he-tree-vue'
...
getItemgroupsTree() {
                Itemgroup.fetchTree(308)
                    .then(data => {
                        this.item_groups_tree = data.item_groups_tree;
                        walkTreeData(this.item_groups_tree, node => {
                            this.$set(node, '$folded', true)
                        })
                    })
                    .catch(error => {});
            },
```

**Comment by miyasinarafat** [comment]
Thanks so much. It's working now and I made a mistake with `walkTreeData`. anyways thanks again for your wonderful support.
