### ISSUE TITLE
Draggable error

### ISSUE THREAD

**Issue by MinhHieuC4E** [phphe/he-tree-vue#51]
Hi @phphe, I have an error with your new update in version 2.0.9. It seem like when i drag child to the new parent node the path of parent has been changed and the child move to wrong place, if the parent is the last of list then i got an error like that: 

![](https://1.bp.blogspot.com/-P6ajD3y-Ca0/YHldK1zCVyI/AAAAAAAAAko/-9TV3LKzqekZ_7x-nt0nH0JTsKK7HYldwCNcBGAsYHQ/s16000/6NBDB5L%2B-%2BImgur.png)

**Comment by phphe** [comment]
fixed in 2.0.10
