### ISSUE TITLE
Problem with targetPath at nested branches

### ISSUE THREAD

**Issue by schrodinger-cat** [phphe/he-tree-vue#55]
I have strange `targetPath` in the store at drag event. You can see it here - https://codesandbox.io/s/hardcore-jackson-nr5xl?file=/src/App.vue

when I drop first element to second position I expect, that `targetPath` be `[0, 1]`, but now it `[0, 2]`. in the DOM `data-tree-node-path` updated correctlly

**Comment by phphe** [comment]
I just published 2.0.1-1.beta.3, please try.

**Comment by schrodinger-cat** [comment]
Sandbox cant load dependency, may be later. I cant try it right now at the normal enviroment, tommorow I will send you full feedback.

Anyway, thanks for your work.

**Comment by schrodinger-cat** [comment]
I tested 2.0.1-1.beta.3, and it work correct. Sometimes i catch issue, when `oneMoveStore` is empty (it returns `{}`), but i really dont know that is a bug or feature :) anyway in my case it dont really needed, i watch only prepend action, to send correct type to server

thank you

**Comment by phphe** [comment]
`oneMoveStore` is for every move event. It is created when move start, destroied when move end. In event `drag`, it is destroied.

**Comment by glutaminefree** [comment]
This issue returned. I'm using version 2.0.10 and when i drag element after another in same branch - index of dragged element increased by 1. When i put dragged element before another - all fine.

![bug](https://user-images.githubusercontent.com/2122419/140056909-9f6c2bcc-358b-4bcd-8ccd-3b5866131620.gif)
