### ISSUE TITLE
Expand all ancestors

### ISSUE THREAD

**Issue by JohnnyMaynne** [phphe/he-tree-vue#68]
Hello. Is it possible to expand all ancestors for a particular node. I want to create a list of pages and when visiting subpages expand their ancestors.

**Comment by phphe** [comment]
here is example. change path to yours.
```js
const path = [5,1,1]
tree.foldAll() // fold all nodes
path.forEach((v, i) => {
  tree.unfold(tree.getNodeByPath(path.slice(0, i+1)))
});
```

**Comment by JohnnyMaynne** [comment]
Thanks for the reply, but I am getting an error:


![image](https://user-images.githubusercontent.com/26120256/152512477-14a92ed6-83b4-4657-84ca-267ac2efe2f5.png)

Here is the code that I will use:

![image](https://user-images.githubusercontent.com/26120256/152513150-a7d0405b-d16b-415c-a445-d9cd026469f3.png)

**Comment by phphe** [comment]
foldAll should be this.$refs.tree.foldAll(). And try short path first. Make sure the path is right.

**Comment by JohnnyMaynne** [comment]
For `foldAll` I used `import {foldAll} from 'he-tree-vue'`

I wrapped the code in setTimeout and he earned, but for some reason it seems to me that this is not a very clean approach:


![image](https://user-images.githubusercontent.com/26120256/152514503-7fa0eb10-c103-42f0-a199-1d1c66d73c9e.png)

**Comment by JohnnyMaynne** [comment]
Either way, it works. Thanks for the help👍
