### ISSUE TITLE
Problem use he-tree-vue

### ISSUE THREAD

**Issue by Archie1978** [phphe/he-tree-vue#69]
I have trouble using your package in version he-tree-vue@4.0.0-beta.2 and vue@3.0.0 on the project https://github.com/phphe/vue-cli-typescript-he-tree-test. I have its error messages but I can't find the problem. Can you help me ?

![image](https://user-images.githubusercontent.com/17623204/154863135-12cb8795-6677-4141-9784-b6d966b4b851.png)

he-tree-vu not found into components/ServersTreeView/index.tsx  and type/index.

**Comment by phphe** [comment]
use he-tree-vue@3

**Comment by phphe** [comment]
npm install he-tree-vue@3

**Comment by Archie1978** [comment]
Yes it is a version 3.

    "core-js": "^3.6.5",
    "he-tree-vue": "3",
    "vue": "^3.0.0",
    "vue-class-component": "^8.0.0-0",
    "vue-property-decorator": "^9.1.2",
    "vue-router": "^4.0.0-0",
    "vue-tsx-support": "^3.2.0",
    "vuex": "^4.0.0-0"

**Comment by phphe** [comment]
The example use v1. Some types like prop_draggable_droppable are private in v3. I'm not going to fix it. I recommend [@he-tree/vue](https://hetree.phphe.com/)

**Comment by Archie1978** [comment]
Great thanks you :+1:
