### ISSUE TITLE
Droppable false not working

### ISSUE THREAD

**Issue by BOISSARD** [phphe/he-tree-vue#70]
## Greetings

First of all, thank you for your work on this package, it's the best available on internet for vuejs.

It's very complete, that's great, even if the documentation is missing examples for complexes parts.

## Issue

`droppable` in the node as :
```
{ text: 'undroppable node', droppable: false },
```
not working, you still can drag and drop in the undroppable node.

[jsfiddle](https://jsfiddle.net/x3ydawq5/2/)

## Context

Installed via npm : `he-tree-vue@2`

**Comment by phphe** [comment]
use `$droppable` in a node

**Comment by BOISSARD** [comment]
Excellent, thanks a lot for your work

**Comment by mayank30** [comment]
@phphe  @BOISSARD  Its not working with latest version 
have you guys tried it..
