### ISSUE TITLE
is working in ie11 with nuxt?

### ISSUE THREAD

**Issue by Drogwur** [phphe/he-tree-vue#8]

**Comment by phphe** [comment]
work in ie11. work in nuxt. not tested in both ie11 and nuxt.

**Comment by Drogwur** [comment]
http://joxi.ru/GrqLgonS49Qw6A
http://joxi.ru/RmzqkWJiY407nr
ie11

**Comment by Drogwur** [comment]
Предполагается наличие ':'

**Comment by phphe** [comment]
thank you for your issue. I checked and tried nuxt and vue-cli, then I found a important issue. 
The solution is add related dependencies in build.transpile of nuxt.config.js.
```js
module.exports = {
  build: {
    transpile: ['he-tree-vue', 'helper-js', 'draggable-helper', 'vue-functions', 'drag-event-service'],
  }
}
```
I added the detail into docs: https://he-tree-vue.phphe.com/transpile.html
